[project]
name = "library-management-system"
version = "0.1.0"
description = "Learning API for personal purpose"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "Flask-SQLAlchemy==3.1.1"
]
